### ISSUE TITLE
 AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'

### ISSUE THREAD

**Issue by XeoPlay** [ducaale/nyan#2]
That happens when trying to 'pip install nyan'.

**Comment by ducaale** [comment]
Hi, could you write down the following:
- python version `python --version`
- setuptools version `python -m easy_install --version`

I suspect the issue you are facing is related to this https://github.com/pypa/setuptools/issues/1694

**Comment by XeoPlay** [comment]
Python 3.8.1
setuptools 41.2.0

**Comment by ducaale** [comment]
Could you try installing Nyan with `pip install --no-use-pep517 nyan`?

**Comment by ducaale** [comment]
Are you sure that you are running the command inside the game directory?

> And what do the "-h" and "-d" do?

`-h` is for displaying `nyan-packager` usage while `-d` is for showing the console output in case you have errors and you would like to debug it.

**Comment by XeoPlay** [comment]
I ran the command inside the game directory.
I got this.
**SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if path is not '' and not os.path.exists(path):
Unable to find "C:\Users\Гриша\Desktop\exe test\assets\*" when adding binary and data files.**

("C:\Users\Гриша\Desktop\exe test\) is the directory of the game.

**Comment by ducaale** [comment]
Ah, that is a bug from my side which I need to fix. In the meantime, could you try creating a folder named `assets` inside the game directory then rerunning the command again?

**Comment by XeoPlay** [comment]
Rerunning the command with the `assets` folder doesn't work.

**Comment by ducaale** [comment]
It should be fixed now. could you try updating Nyan to the latest version?
```
pip install --upgrade --no-use-pep517 nyan
```

**Comment by XeoPlay** [comment]
Thanks for playing my game! I will add all of the things that you just listed in the future)
I updated nyan to 0.8.0 with the `pip install --upgrade --no-use-pep517 nyan` command,
and got the same error. I will copy-paste how I typed the command and the error.
```
C:\Users\Гриша\Desktop\exe test>nyan-packager whackamole.py
c:\users\гриша\appdata\local\programs\python\python38-32\lib\site-packages\win32com\client\makepy.py:369: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if path is not '' and not os.path.exists(path):
```

**Comment by ducaale** [comment]
This is just a warning from one of pyinstaller dependencies. You will find your packaged game inside the dist folder.

**Comment by XeoPlay** [comment]
I found and opened the game file. It was a black screen for a few seconds and then it closed.

**Comment by ducaale** [comment]
ok, that was another thing that needed to be fixed. could try updating Nyan and rerunning the command again.

**Comment by XeoPlay** [comment]
I tried. Still a black screen for 2 seconds and then it shuts off.

**Comment by ducaale** [comment]
In that case, you can add the `-d` flag to `nyan-packager` to enable console output so we can see the current error.

```
nyan-packager -d your_game.py
```

Then run your_game.exe from the commandline.

**Comment by XeoPlay** [comment]
No console output except the SyntaxWarning. And the screen is still black.

**Comment by ducaale** [comment]
Hmm, I think you haven't updated Nyan yet. You shouldn't be getting SyntaxWarning on Nyan v0.8.1

**Comment by XeoPlay** [comment]
Turns out I memorized the `pip install --upgrade --no-use-pep517` command wrong. Thank you so much! It worked! One last question: is there a way to use `nyan-packager` so there's only one file?

**Comment by ducaale** [comment]
Yes, but you will have to update to Nyan v0.9.0. Here is how you can create a single .exe file
```
nyan-packager --onefile your_game.py
```

Note that this makes the game startup slower, at least that is the case on my laptop.

**Comment by XeoPlay** [comment]
Ok thanks! Thank you for your help!
